### ISSUE TITLE
cudnn和cuda版本？

### ISSUE THREAD

**Issue by zoulingqi** [Le-Xiaohuai-speech/DPCRN_DNS3#11]
你好，能告诉我你用的cudnn和cuda版本号吗？我似乎在这里遇到了点问题

**Comment by Le-Xiaohuai-speech** [comment]
cuda 10.1cudnn 7.6.5 tf 1.15推荐使用conda安装



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月26日(周三) 下午2:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Le-Xiaohuai-speech/DPCRN_DNS3] cudnn和cuda版本？ (Issue #11)




 
你好，能告诉我你用的cudnn和cuda版本号吗？我似乎在这里遇到了点问题
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zoulingqi** [comment]
多谢，那可能是驱动有点问题
