### ISSUE TITLE
你好，可以请教一下是否对数据集进行了预处理呢？

### ISSUE THREAD

**Issue by shinobuwz** [Le-Xiaohuai-speech/DPCRN_DNS3#12]
在data_loader中噪声文件和纯净文件的编号似乎是一一对应的，例如clean_speech=clean_file_1，那对应读取的噪声就是noise_file_1。为什么不采取分别从噪声文件夹和人声文件夹随机读取一个文件进行叠加呢？

**Comment by Le-Xiaohuai-speech** [comment]
并没有太多数据预处理和增强，只有切片和随机信噪比。可以考虑的增强有随机增益，随机选择噪声文件，随机切分，随机信道滤波器等等都是可以用于数据预处理的。具体参考这篇论文： S. Braun and I. Tashev, “Data augmentation and loss normalization for deep noise suppression,” in Proc. Speech Comput. Springer, 2020, pp. 79–86.

**Comment by shinobuwz** [comment]
> 并没有太多数据预处理和增强，只有切片和随机信噪比。可以考虑的增强有随机增益，随机选择噪声文件，随机切分，随机信道滤波器等等都是可以用于数据预处理的。具体参考这篇论文： S. Braun and I. Tashev, “Data augmentation and loss normalization for deep noise suppression,” in Proc. Speech Comput. Springer, 2020, pp. 79–86.

谢谢解答！
