### ISSUE TITLE
语音增强效果

### ISSUE THREAD

**Issue by leyangxing** [Le-Xiaohuai-speech/DPCRN_DNS3#18]
作者大大，请问为什么在下列noisy_trainset_28spk_wav的数据集中去噪后的语音严重失真？我训练的模型和你提供的模型都出现严重失真？
![image](https://user-images.githubusercontent.com/87252340/165073358-6ef8f68a-2bc6-411c-83a4-b1b00f9d7caa.png)

**Comment by Le-Xiaohuai-speech** [comment]
vctk-demand数据集是48k采样率的吧。你得降到16k



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月25日(周一) 晚上6:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Le-Xiaohuai-speech/DPCRN_DNS3] 语音增强效果 (Issue #18)




 
作者大大，请问为什么在下列noisy_trainset_28spk_wav的数据集中去噪后的语音严重失真？我训练的模型和你提供的模型都出现严重失真？

**Comment by leyangxing** [comment]
谢谢啦，我解决啦
