### ISSUE TITLE
tflite streaming frame size is not the same as  "real_time_DPCRN.py" script

### ISSUE THREAD

**Issue by xxoospring** [Le-Xiaohuai-speech/DPCRN_DNS3#21]
Hi, why the processing frame size in recording.py is not the same as real_time_DPCRN.py? 512 point fft in tflite model demo, but 200 fft in h5 model demo

**Comment by xxoospring** [comment]
Sorry, I just saw your readme!  请超快的速度读下面一段话：
**哥们儿，哥们儿，哥们儿，打工吗？ 来小米吗，来小米吗，不是大米，不是黑米，不能吃，不能吃，在南京，南京，床上翻个身就到工位了，不懂直接问Daniel**

**Comment by Le-Xiaohuai-speech** [comment]
it is a smaller model.



---Original---
From: ***@***.***&gt;
Date: Fri, Jun 10, 2022 15:53 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Le-Xiaohuai-speech/DPCRN_DNS3] tflite streaming frame size is notthe same as  "real_time_DPCRN.py" script (Issue #21)




 
Hi, why the processing frame size in recording.py is not the same as real_time_DPCRN.py? 512 point fft in tflite model demo, but 200 fft in h5 model demo
